version: '2'
services:
  mongo:
    build: .
    image: dockerthreepoint
    environment:
      - MONGO_DATABASE=threepoint
    ports:
      - "27017:27017"
    volumes:
      - /Users/josefelixestevezhernandez/mongodisk:/data/db
    entrypoint: /loadData.sh
    command: mongod
  api:
    image: api
    environment:
      - MONGODB_CONNSTRING="mongodb://appuser:supersecret@mongo:27017/test?authSource=admin"
    ports:
      - "3000:3000"
